name: drupal-postgre
recipe: drupal8
config:
  php: '7.2'
  webroot: web
  database: postgres
  conf:
    php: php.ini
proxy:
  appserver:
      - customers-portal-postgre.lndo.site
      - amos-portal-postgre.lndo.site
      - atos-portal-postgre.lndo.site
      - admin-portal-postgre.lndo.site
  


  
