<?php 

function eauthority_dashboards_theme($existing, $type, $theme, $path) {
  return [
    'taskconsole_status_bar' => [
      'variables' => [
        'stage_count' => 0,
        'stage_messages' => [],
        'current_stage' => 0,
        'current_stage_message' => ''],
    ],
    
    'portal_taskconsole_views' => [
      'variables' => [
        'task_information' => '',  //the html string of task information
        'title' => '',
      ],
    ],

    'eauthority_dashboards' => [
      'variables' => [
        'taskconsole' => '',  
      ],
    ],
  ];
}


